// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab2and3.Models.Repositories;

namespace lab2and3.Migrations
{
    [DbContext(typeof(TrsContext))]
    [Migration("20211212130449_initial-with-all-tables")]
    partial class initialwithalltables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("lab2and3.Models.DomainModel.Activity", b =>
                {
                    b.Property<string>("ActivityId")
                        .HasColumnType("varchar(767)");

                    b.Property<int?>("AcceptedBudget")
                        .HasColumnType("int");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ActivityId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("varchar(767)");

                    b.HasKey("UserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.UsersMonth", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<bool>("Frozen")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserLogin", "Month", "Year");

                    b.ToTable("UsersMonths");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.Activity", b =>
                {
                    b.HasOne("lab2and3.Models.DomainModel.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("lab2and3.Models.DomainModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.Project", b =>
                {
                    b.HasOne("lab2and3.Models.DomainModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.User", b =>
                {
                    b.HasOne("lab2and3.Models.DomainModel.Project", null)
                        .WithMany("Users")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("lab2and3.Models.DomainModel.Project", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
